### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by iDoka** [zack-bitcoin/amoveo-c-miner#16]
C program unexpected crashes by startup:
```
$ ./amoveo_c_miner 
Segmentation fault (core dumped)
```

My debug for reveal root of causes (gdb build):
```
$ gcc -O0 -g -std=c99 -c sha256.c
$ gcc -O0 -g -std=c99 -c amoveo_pow.c
$ gcc sha256.o amoveo_pow.o -o amoveo_c_miner
$ gdb ./amoveo_c_miner

GNU gdb (GDB) Red Hat Enterprise Linux 8.0.1-26.el7.sc1
Copyright (C) 2017 Free Software Foundation, Inc.
Reading symbols from ./amoveo_c_miner...done.
(gdb) run
Starting program: /home/doka/proj/2019/amoveo-c-miner/amoveo_c_miner 
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7_4.2.x86_64

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7a8b60c in fseek () from /lib64/libc.so.6

(gdb) backtrace
#0  0x00007ffff7a8b60c in fseek () from /lib64/libc.so.6
#1  0x000000000040155f in read_input (B=0x7fffffffd3b0 "", N=0x7fffffffd390 "\t", id=0) at amoveo_pow.c:114
#2  0x00000000004016d1 in main (argc=1, argv=0x7fffffffd4e8) at amoveo_pow.c:151
(gdb) 
```

It seems root of cause the string 114:
```
fseek(fileptr, 0, SEEK_END); // Jump to the end of the file
```

I try to manually create file `mining_input` (from previous string: `fileptr = fopen("mining_input", "rb");`) and crashes stops.

**Comment by zack-bitcoin** [comment]
Looks like you didn't read the instructions on the README.
https://github.com/zack-bitcoin/amoveo-c-miner

I don't see any errors in your description of the software, it looks like
everything is working normally.

**Comment by zack-bitcoin** [comment]
I updated the main branch to use the post-update version of the code.

**Comment by iDoka** [comment]
Thanks for updating master branch!
